version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: home_page_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-root}
      POSTGRES_DB: ${POSTGRES_DB:-portefolio}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

