/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorksIdImport } from './routes/works/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const WorksIndexLazyImport = createFileRoute('/works/')()
const QuantumIndexLazyImport = createFileRoute('/quantum/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WorksIndexLazyRoute = WorksIndexLazyImport.update({
  path: '/works/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/works/index.lazy').then((d) => d.Route))

const QuantumIndexLazyRoute = QuantumIndexLazyImport.update({
  path: '/quantum/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/quantum/index.lazy').then((d) => d.Route))

const WorksIdRoute = WorksIdImport.update({
  path: '/works/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/works/$id': {
      preLoaderRoute: typeof WorksIdImport
      parentRoute: typeof rootRoute
    }
    '/quantum/': {
      preLoaderRoute: typeof QuantumIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/works/': {
      preLoaderRoute: typeof WorksIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  WorksIdRoute,
  QuantumIndexLazyRoute,
  WorksIndexLazyRoute,
])

/* prettier-ignore-end */
