/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const WorksIndexLazyImport = createFileRoute('/works/')()
const WorksIdLazyImport = createFileRoute('/works/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WorksIndexLazyRoute = WorksIndexLazyImport.update({
  path: '/works/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/works/index.lazy').then((d) => d.Route))

const WorksIdLazyRoute = WorksIdLazyImport.update({
  path: '/works/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/works/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/works/$id': {
      preLoaderRoute: typeof WorksIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/works/': {
      preLoaderRoute: typeof WorksIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  WorksIdLazyRoute,
  WorksIndexLazyRoute,
])

/* prettier-ignore-end */
