// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, title: string, description: string, shorten_description: string, image_url: string, github_url: string, project_url: string | null, file_uri: string | null, is_sio: boolean, };