name: dprint check

on:
  push:
    paths:
      - front_vite/**
      - .github/workflows/dprint.yaml

defaults:
  run:
    working-directory: ./front_vite/

jobs:
  dprint-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front_vite/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run dprint
        uses: dprint/check@v2.2
