name: dprint check

on:
  push:
    paths:
      - front_vite/**
      - .github/workflows/dprint.yaml

jobs:
  dprint-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./front_vite"
    name: check
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
